# Generated by Django 4.1.2 on 2022-10-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcsHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('val1', models.IntegerField(default=0, verbose_name='Первое значение')),
                ('val2', models.IntegerField(default=0, verbose_name='Второе значение')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('result', models.IntegerField(verbose_name='Результат')),
                ('operator', models.CharField(max_length=1, verbose_name='Оператор')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
